import time

def print2(a):
    for i in a:
        print(i, end="", flush=True)
        time.sleep(0.01)
    print()


print2("Steamed Hams: The Game")
print2("Use the numbers to choose options")
print()
print2("1:Begin")
query=input(">>> ")
if query == "1":
    print()
    print2("Chalmers: Well, Seymour, I made it, despite your directions.")
    print()
    print2("1:Aggressive and rude insult")
    print2("2:Overly friendly greeting")
    query=input(">>> ")
    print()
    if query == "1":
        print2("Skinner: You fat-headed buffoon! The directions I gave you were perfectly in order! Plus you've already been here, so you must know the way!")
        print2("Chalmers: Seymour! I have never been more insulted in my life! You're fired!")
        print()
        print2("Ending: Fired")
    elif query == "2":
        print2("Skinner: Ah, Superintendent Chalmers, welcome. I hope you're prepared for an unforgettable luncheon!")
        print2("Chalmers: Yeah.")
        print2("[Skinner enters the kitchen, soon realising that his roast is ruined.]")
        print2("Skinner: Oh, egads! My roast is ruined!")
        print()
        print2("1: Tell the truth")
        print2("2: Lie and purchase fast food")
        query=input(">>> ")
        print()
        if query == "1":
            print2("Skinner: Superintendent! The roast is on fire!")
            print2("Chalmers: Good lord! We have to put it out!")
            print2("Skinner and Chalmers extinguish the fire before any harm occurs.")
            print2("Chalmers: Well, Seymour, we saved the house, but the roast is unrecoverable.")
            print2("Skinner: Well, there's a Krusty Burger just over there. We could have that.")
            print2("Chalmers: Krusty Burger. Yes, I do enjoy the food there. I suppose we could.")
            print2("[Skinner and Chalmers consume the Krusty Burgers.]")
            print2("Chalmers: Well Seymour, that was quite enjoyable, but I must go now. I will see you at work tomorrow.")
            print()
            print2("Ending: Honest Abe")
        elif query == "2":
            print2("Skinner: But what if I were to purchase fast food and disguise it as my own cooking? [chuckles] Delightfully devilish, Seymour.")
            print2("[Chalmers enters the kitchen, viewing Skinner attempting to escape out of the window]")
            print2("Chalmers: SEEEEEYMOOUUURRR!!!")
            print()
            print2("1: Tell the truth")
            print2("2: Opening a window")
            print2("3: Streching your calves on the windowsill")
            print2("4: Skydiving")
            query=input(">>> ")
            print()
            if query == "1":
                print2("Skinner: Superintendent! The roast is on fire, I-")
                print2("Chalmers: And you were climbing out of the window to escape?")
                print2("Skinner: No, I was just-")
                print2("Chalmers: Good lord, Seymour! Aren't you a member of the Springfield Voluntary Fire Department? You haven't alerted me or your mother! We could have been seriously injured!")
                print2("Skinner: Well, now that you put it like that, I think-")
                print2("Chalmers: That's it, Seymour! You're fired!")
                print()
                print2("Ending: Fired")
            elif query == "2":
                print2("Skinner: Superintendent! I was just opening a window to let the smoke out.")
                print2("Chalmers: Smoke? What smoke? Good lord, the oven is on fire!")
                print2("Skinner: Uh, I meant that I was, uh-")
                print2("Chalmers: Seymour, you were clearly climbing out of the window to escape!")
                print2("Skinner: Ooh, uh, I was, uh, just, um-")
                print2("Chalmers: That's it, Seymour! I'm firing you for lack of safety and neglect!")
                print()
                print2("Ending: Fired")
            elif query == "4":
                print2("Skinner: Superintendent! I was just skydiving out of the window!")
                print2("Chalmers: What?")
                print()
                print2("Ending: What")
            elif query == "3":
                print2("Skinner: Superintendent! I was just, uh, just stretching my calves on the windowsill. Isometric exercise! Care to join me?")
                print2("Chalmers: Why is there smoke coming out of your oven, Seymour?")
                print()
                print2("1: Tell the truth")
                print2("2: Make up an excuse")
                query=input(">>> ")
                print()
                if query == "1":
                    print2("Skinner: The roast is on fire!")
                    print2("Chalmers: Good lord! And you were climbing out of the window to escape? You know what, Seymour, you're fired!")
                    print()
                    print2("Ending: The Seymour is fired!")
                elif query == "2":
                    print2("Skinner: Uh... ooh! That isn't smoke, it's steam! Steam from the steamed clams we're having. Mmmm, steamed clams!")
                    print2("[Chalmers leaves, and Seymour climbs out the window to purchase Krusty Burger]")
                    print2("Skinner: Superintendent, I hope you're ready for some mouthwatering hamburgers.")
                    print2("Chalmers: I thought we were having steamed clams.")
                    print()
                    print2("1: Tell the truth")
                    print2("2: Make up an excuse")
                    query=input(">>> ")
                    print()
                    if query == "1":
                        print2("Skinner: To tell the truth, Superintendent, the roast caught fire, but I just wanted this to be perfect, so I purchased fast food.")
                        print2("Chalmers: Look, Seymour, we've worked together for over 30 years. You can tell me when something's wrong, but we have to save your mother and call the fire department. We can reschedule the meeting, how about it, Seymour?")
                        print()
                        print2("Ending: Cancelled Luncheon")
                    elif query == "2":
                        print2("Skinner: Oh no, I said steamed hams. That's what I call hamburgers.")
                        print2("Chalmers: You call hamburgers steamed hams?")
                        print2("Skinner: Yes. It's a regional dialect.")
                        print2("Chalmers: Uh-huh. Eh, what region?")
                        print2("Skinner: Uh...")
                        print()
                        print2("1: Upstate New York")
                        print2("2: Russia")
                        query=input(">>> ")
                        print()
                        if query == "1":
                            print2("Skinner: Upstate New York.")
                            print2("Chalmers: Really? Well I'm from Utica and I've never heard anyone use the phrase steamed hams.")
                            print2("Skinner: Oh, not in Utica, no. It's an Albany expression.")
                            print2("Chalmers: I see.")
                            print2("Chalmers: You know, these hamburgers are quite similar to the ones they have at Krusty Burger.")
                            print()
                            print2("1: Tell the truth")
                            print2("2: 'Old Family Recipe'")
                            query=input(">>> ")
                            print()
                            if query == "1":
                                print2("Skinner: Well, that's because they are.")
                                print2("Chalmers: What?! You're telling me that you bought Krusty Burgers and served them to me as your own- good lord, what is happening in there?!")
                                print()
                                print2("1: Fire")
                                print2("2: Roboticiser")
                                print2("3: Aurora Borealis")
                                query=input(">>> ")
                                print()
                                if query == "1":
                                    print2("Skinner: The kitchen in on fire!")
                                    print2("Chalmers: Good lord! We have to save your mother and call the fire department!")
                                    print2("[Agnes is saved and the fire department arrive to extinguish Skinner's house]")
                                    print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                    print()
                                    print2("Ending: Unforgettable Luncheon, but not in a good way")
                                elif query == "2":
                                    print2("Skinner: Roboticiser.")
                                    print2("Chalmers: Wha-")
                                    print2("[Robotnik steps out of the kitchen, causing Skinner to die of a heart attack]")
                                    print()
                                    print2("Ending: Saturday Morning Ending")
                                elif query == "3":
                                    print2("Skinner: Aurora Borealis.")
                                    print2("Chalmers: A-Aurora Borealis!?")
                                    print2("Chalmers: At this time of year,")
                                    print2("Chalmers: At this time of day,")
                                    print2("Chalmers: In this part of the country,")
                                    print2("Chalmers: Localised entirely within your kitchen!?")
                                    print()
                                    print2("1: Yes")
                                    print2("2: No")
                                    query=input(">>> ")
                                    print()
                                    if query == "1":
                                        print2("Skinner: Yes.")
                                        print2("Chalmers: May I see it?")
                                        print()
                                        print2("1: Yes")
                                        print2("2: No")
                                        query=input(">>> ")
                                        print()
                                        if query == "1":
                                            print2("Skinner: Yes.")
                                            print2("[Skinner and Chalmers enter the kitchen, viewing The Northern Lights up close.]")
                                            print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                            print()
                                            print2("Ending: Unforgettable Luncheon")
                                        elif query == "2":
                                            print2("Skinner: No.")
                                            print2("[Skinner and Chalmers exit the house]")
                                            print2("Agnes: Seymour! The house is on fire!")
                                            print2("Skinner: No, mother, it's just the Northern Lights.")
                                            print2("Chalmers: Well, Seymour, you are an odd fellow, but I must say, you steam a good ham.")
                                            print2("Agnes: Help! HELP!!!")
                                            print2("[Skinner shows Chalmers a thumbs up and Chalmers heads home")
                                            print()
                                            print2("Ending: Homeless")
                                    elif query == "2":
                                        print2("Skinner: No, it's fire.")
                                        print2("Chalmers: Good lord, you're joking when there's a fire?! You know what?  I'm firing you, just for your neglegence!")
                                        print()
                                        print2("Ending: Fired")
                            if query == "2":
                                print2("Skinner: Hohoho, no! Patented Skinner Burgers. Old family recipe!")
                                print2("Chalmers: For steamed hams?")
                                print2("Skinner: Yes.")
                                print2("Chalmers: Yes, and you call them steamed hams, despite the fact they are obviously grilled.")
                                print2("Skinner: Y- Uh.. you know, the... One thing I should... excuse me for one second.")
                                print2("Chalmers: Of course.")
                                print2("[Skinner enters the kitchen for a couple seconds before leaving again, and returning.")
                                print2("Skinner: [BIG YAWN] Well, that was wonderful. A good time was had by all. I'm pooped.")
                                print2("Chalmers: Yes, I should be-good lord, what is happening in there?!")
                                print()
                                print2("1: Fire")
                                print2("2: Roboticiser")
                                print2("3: Aurora Borealis")
                                query=input(">>> ")
                                print()
                                if query == "1":
                                    print2("Skinner: The kitchen in on fire!")
                                    print2("Chalmers: Good lord! We have to save your mother and call the fire department!")
                                    print2("[Agnes is saved and the fire department arrive to extinguish Skinner's house]")
                                    print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                    print()
                                    print2("Ending: Unforgettable Luncheon, but not in a good way")
                                elif query == "2":
                                    print2("Skinner: Roboticiser.")
                                    print2("Chalmers: Wha-")
                                    print2("[Robotnik steps out of the kitchen, causing Skinner to die of a heart attack]")
                                    print()
                                    print2("Ending: Saturday Morning Ending")
                                elif query == "3":
                                    print2("Skinner: Aurora Borealis.")
                                    print2("Chalmers: A-Aurora Borealis!?")
                                    print2("Chalmers: At this time of year,")
                                    print2("Chalmers: At this time of day,")
                                    print2("Chalmers: In this part of the country,")
                                    print2("Chalmers: Localised entirely within your kitchen!?")
                                    print()
                                    print2("1: Yes")
                                    print2("2: No")
                                    query=input(">>> ")
                                    print()
                                    if query == "1":
                                        print2("Skinner: Yes.")
                                        print2("Chalmers: May I see it?")
                                        print()
                                        print2("1: Yes")
                                        print2("2: No")
                                        query=input(">>> ")
                                        print()
                                        if query == "1":
                                            print2("Skinner: Yes.")
                                            print2("[Skinner and Chalmers enter the kitchen, viewing The Northern Lights up close.]")
                                            print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                            print()
                                            print2("Ending: Unforgettable Luncheon")
                                        elif query == "2":
                                            print2("Skinner: No.")
                                            print2("[Skinner and Chalmers exit the house]")
                                            print2("Agnes: Seymour! The house is on fire!")
                                            print2("Skinner: No, mother, it's just the Northern Lights.")
                                            print2("Chalmers: Well, Seymour, you are an odd fellow, but I must say, you steam a good ham.")
                                            print2("Agnes: Help! HELP!!!")
                                            print2("[Skinner shows Chalmers a thumbs up and Chalmers heads home")
                                            print()
                                            print2("Ending: Homeless")
                                    elif query == "2":
                                        print2("Skinner: No, it's fire.")
                                        print2("Chalmers: Good lord, you're joking when there's a fire?! You know what?  I'm firing you, just for your neglegence!")
                                        print()
                                        print2("Ending: Fired")
                        elif query == "2":
                            print2("Skinner: Russia.")
                            print2("Chalmers: Look, Seymour, I know your family history - you're not from Russia.")
                            print2("Skinner: Oh. Uh, upstate New York?")
                            print2("Chalmers: Really? Well I'm from Utica and I've never heard anyone use the phrase steamed hams.")
                            print2("Skinner: Oh, not in Utica, no. It's an Albany expression.")
                            print2("Chalmers: I see.")
                            print2("Chalmers: You know, these hamburgers are quite similar to the ones they have at Krusty Burger.")
                            print()
                            print2("1: Tell the truth")
                            print2("2: 'Old Family Recipe'")
                            query=input(">>> ")
                            print()
                            if query == "1":
                                print2("Skinner: Well, that's because they are.")
                                print2("Chalmers: What?! You're telling me that you bought Krusty Burgers and served them to me as your own- good lord, what is happening in there?!")
                                print()
                                print2("1: Fire")
                                print2("2: Roboticiser")
                                print2("3: Aurora Borealis")
                                query=input(">>> ")
                                print()
                                if query == "1":
                                    print2("Skinner: The kitchen in on fire!")
                                    print2("Chalmers: Good lord! We have to save your mother and call the fire department!")
                                    print2("[Agnes is saved and the fire department arrive to extinguish Skinner's house]")
                                    print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                    print()
                                    print2("Ending: Unforgettable Luncheon, but not in a good way")
                                elif query == "2":
                                    print2("Skinner: Roboticiser.")
                                    print2("Chalmers: Wha-")
                                    print2("[Robotnik steps out of the kitchen, causing Skinner to die of a heart attack]")
                                    print()
                                    print2("Ending: Saturday Morning Ending")
                                elif query == "3":
                                    print2("Skinner: Aurora Borealis.")
                                    print2("Chalmers: A-Aurora Borealis!?")
                                    print2("Chalmers: At this time of year,")
                                    print2("Chalmers: At this time of day,")
                                    print2("Chalmers: In this part of the country,")
                                    print2("Chalmers: Localised entirely within your kitchen!?")
                                    print()
                                    print2("1: Yes")
                                    print2("2: No")
                                    query=input(">>> ")
                                    print()
                                    if query == "1":
                                        print2("Skinner: Yes.")
                                        print2("Chalmers: May I see it?")
                                        print()
                                        print2("1: Yes")
                                        print2("2: No")
                                        query=input(">>> ")
                                        print()
                                        if query == "1":
                                            print2("Skinner: Yes.")
                                            print2("[Skinner and Chalmers enter the kitchen, viewing The Northern Lights up close.]")
                                            print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                            print()
                                            print2("Ending: Unforgettable Luncheon")
                                        elif query == "2":
                                            print2("Skinner: No.")
                                            print2("[Skinner and Chalmers exit the house]")
                                            print2("Agnes: Seymour! The house is on fire!")
                                            print2("Skinner: No, mother, it's just the Northern Lights.")
                                            print2("Chalmers: Well, Seymour, you are an odd fellow, but I must say, you steam a good ham.")
                                            print2("Agnes: Help! HELP!!!")
                                            print2("[Skinner shows Chalmers a thumbs up and Chalmers heads home")
                                            print()
                                            print2("Ending: Homeless")
                                    elif query == "2":
                                        print2("Skinner: No; I was joking. It is actually a fire. It would be wise to contact the local authorities.")
                                        print2("Chalmers: Good lord, you're joking when there's a fire?! You know what?  I'm firing you, just for your neglegence!")
                                        print()
                                        print2("Ending: Fired")
                            elif query == "2":
                                print2("Skinner: Hohoho, no! Patented Skinner Burgers. Old family recipe!")
                                print2("Chalmers: For steamed hams?")
                                print2("Skinner: Yes.")
                                print2("Chalmers: Yes, and you call them steamed hams, despite the fact they are obviously grilled.")
                                print2("Skinner: Y- Uh.. you know, the... One thing I should... excuse me for one second.")
                                print2("Chalmers: Of course.")
                                print2("[Skinner enters the kitchen for a couple seconds before leaving again, and returning.")
                                print2("Skinner: [BIG YAWN] Well, that was wonderful. A good time was had by all. I'm pooped.")
                                print2("Chalmers: Yes, I should be-good lord, what is happening in there?!")
                                print()
                                print2("1: Fire")
                                print2("2: Roboticiser")
                                print2("3: Aurora Borealis")
                                query=input(">>> ")
                                print()
                                if query == "1":
                                    print2("Skinner: The kitchen in on fire!")
                                    print2("Chalmers: Good lord! We have to save your mother and call the fire department!")
                                    print2("[Agnes is saved and the fire department arrive to extinguish Skinner's house]")
                                    print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                    print()
                                    print2("Ending: Unforgettable Luncheon, but not in a good way")
                                elif query == "2":
                                    print2("Skinner: Roboticiser.")
                                    print2("Chalmers: Wha-")
                                    print2("[Robotnik steps out of the kitchen, causing Skinner to die of a heart attack]")
                                    print()
                                    print2("Ending: Saturday Morning Ending")
                                elif query == "3":
                                    print2("Skinner: Aurora Borealis.")
                                    print2("Chalmers: A-Aurora Borealis!?")
                                    print2("Chalmers: At this time of year,")
                                    print2("Chalmers: At this time of day,")
                                    print2("Chalmers: In this part of the country,")
                                    print2("Chalmers: Localised entirely within your kitchen!?")
                                    print()
                                    print2("1: Yes")
                                    print2("2: No")
                                    query=input(">>> ")
                                    print()
                                    if query == "1":
                                        print2("Skinner: Yes.")
                                        print2("Chalmers: May I see it?")
                                        print()
                                        print2("1: Yes")
                                        print2("2: No")
                                        query=input(">>> ")
                                        print()
                                        if query == "1":
                                            print2("Skinner: Yes.")
                                            print2("[Skinner and Chalmers enter the kitchen, viewing The Northern Lights up close.]")
                                            print2("Chalmers: Well, Seymour, that was an unforgettable luncheon.")
                                            print()
                                            print2("Ending: Unforgettable Luncheon")
                                        elif query == "2":
                                            print2("Skinner: No.")
                                            print2("[Skinner and Chalmers exit the house]")
                                            print2("Agnes: Seymour! The house is on fire!")
                                            print2("Skinner: No, mother, it's just the Northern Lights.")
                                            print2("Chalmers: Well, Seymour, you are an odd fellow, but I must say, you steam a good ham.")
                                            print2("Agnes: Help! HELP!!!")
                                            print2("[Skinner shows Chalmers a thumbs up and Chalmers heads home")
                                            print()
                                            print2("Ending: Homeless")
                                    elif query == "2":
                                        print2("Skinner: No; I was joking. It is actually a fire. It would be wise to contact the local authorities.")
                                        print2("Chalmers: Good lord, you're joking when there's a fire?! You know what?  I'm firing you, just for your neglegence!")
                                        print()
                                        print2("Ending: Fired")
