Name = "SHM Engine"
MajorVersion = "1.2"
Patch = ""
Indev = true
PythonVer = 3.11
ReleaseDate = "2026-07-02"
Dist = "The Shopkeeper's Quest 1.2"
Link = "https://github.com/solidlamp"
SaveVersion = 2
DefaultBorderStyle = 1
Creator = "SolidLamp"
Licence = "MIT"
