# Used for the entry point script

Name = "The Shopkeeper's Quest"
Version = "Experimental"
ReleaseDate = "2026-02-22"
Licence = "MIT License"
Creator = "SolidLamp"
Link = "https://github.com/solidlamp"
