Name  = "SHM Engine"
MajorVersion = "1.2"
Patch = "-dev7"
Indev = true
PythonVer = 3.11
ReleaseDate = "2026-03-30"
Dist = "The Shopkeeper's Quest Experimental"
Link = "https://github.com/solidlamp"
SaveVersion = 1
DefaultBorderStyle = 1
